In [1]:
import numpy as npy
from mindquantum.core import X, Y, Z, H, RX, RY, RZ

In [2]:
print('Gate name:', X)
X.matrix()

Gate name: X


array([[0, 1],
       [1, 0]])

In [3]:
print('Gate name:', Y)
Y.matrix()

Gate name: Y


array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

In [4]:
print('Gate name:', Z)
Z.matrix()

Gate name: Z


array([[ 1,  0],
       [ 0, -1]])

In [5]:
print('Gate name:', H)
H.matrix()

Gate name: H


array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
cnot = X.on(0, 1)
print(cnot)

X(0 <-: 1)


In [7]:
rx = RX('theta')
print('Gate name:', rx)
rx.matrix({'theta': 0})

Gate name: RX(theta)


array([[1.+0.j, 0.-0.j],
       [0.-0.j, 1.+0.j]])

In [8]:
ry = RY('theta')
print('Gate name:', ry)
ry.matrix({'theta': npy.pi/2})

Gate name: RY(theta)


array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [10]:
rz = RZ('theta')
print('Gate name:', rz)
npy.round(rz.matrix({'theta': npy.pi}))

Gate name: RZ(theta)


array([[0.-1.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [11]:
from mindquantum.core import Circuit

encoder = Circuit()
encoder += H.on(0)
encoder += X.on(1, 0)
encoder += RY('theta').on(2)

print(encoder)
encoder.summary()

q0: ──────H────────●──
                   │
q1: ───────────────X──

q2: ──RY(theta)───────
=========Circuit Summary=========
|Total number of gates  : 3.    |
|Parameter gates        : 1.    |
|with 1 parameters are  : theta.|
|Number qubit of circuit: 3     |
